CREATE TABLE "LlamadasSoporte" (
  "IDLlamada" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "FechaLLamada" datetime,
  "DescripcionLLamada" text
);

CREATE TABLE "Habitaciones" (
  "IDHabitacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NumeroHabitacion" varchar(10),
  "TipoHabitacion" habitaciones_tipohabitacion_enum,
  "Estado" habitaciones_estado_enum
);

CREATE TABLE "HabitacionesPacientes" (
  "IDHabitacionPaciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "IDHabitacion" int,
  "FechaAdmision" datetime,
  "FechaAlta" datetime
);

CREATE TABLE "Alergias" (
  "IDAlergia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "NombreAlergia" varchar(100),
  "SeveridadAlergia" alergias_severidad_enum
);

CREATE TABLE "RegistrosMedicos" (
  "IDRegistro" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "IDDoctor" int,
  "FechaRegistro" datetime,
  "DetallesRegistro" text
);

CREATE TABLE "EquipamientoMedico" (
  "IDEquipo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NombreEquipo" varchar(100),
  "TipoEquipo" varchar(50),
  "Estado" equipamiento_estado_enum
);

CREATE TABLE "Citas" (
  "IDCita" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "IDDoctor" int,
  "FechaCita" datetime,
  "Razon" text,
  "Estado" citas_estado_enum
);

CREATE TABLE "HistorialMedicacion" (
  "IDMedicacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "NombreMedicacion" varchar(100),
  "Dosis" varchar(50),
  "FechaInicio" date,
  "FechaFin" date
);

CREATE TABLE "Auxiliares" (
  "IDAuxiliar" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" varchar(50),
  "Apellido" varchar(50),
  "NumeroTelefono" varchar(15),
  "Correo" varchar(50) UNIQUE,
  "IDDoctorAsignado" int,
  "FechaContratacion" date
);

CREATE TABLE "Pagos" (
  "IDPago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "FechaPago" datetime,
  "Monto" decimal(10,2),
  "MetodoPago" pagos_metodo_enum
);

CREATE TABLE "TurnosPersonal" (
  "IDTurno" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPersonal" int,
  "TipoPersonal" turnospersonal_tipo_enum,
  "FechaTurno" date,
  "InicioTurno" time,
  "FinTurno" time
);

CREATE TABLE "GruposApoyoPacientes" (
  "IDGrupoApoyoPaciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "IDGrupoApoyo" int,
  "FechaUnion" datetime
);

CREATE TABLE "GruposApoyo" (
  "IDGrupoApoyo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NombreGrupo" varchar(100),
  "Descripcion" text
);

CREATE TABLE "ResumenesAlta" (
  "IDResumenAlta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "FechaAlta" datetime,
  "Resumen" text
);

CREATE TABLE "Enfermeras" (
  "IDEnfermera" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" varchar(50),
  "Apellido" varchar(50),
  "NumeroTelefono" varchar(15),
  "Correo" varchar(50) UNIQUE,
  "IDDoctorAsignado" int,
  "FechaContratacion" date
);

CREATE TABLE "Inmunizaciones" (
  "IDInmunizacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "NombreInmunizacion" varchar(100),
  "FechaInmunizacion" date
);

CREATE TABLE "CuidadosUrgencias" (
  "IDUrgencia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "FechaAdmision" datetime,
  "FechaAlta" datetime,
  "Estado" urgencias_estado_enum
);

CREATE TABLE "AsignacionesPersonal" (
  "IDAsignacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPersonal" int,
  "TipoPersonal" asignacionespersonal_tipo_enum,
  "IDPaciente" int,
  "FechaAsignacion" datetime
);

CREATE TABLE "ContactosEmergencia" (
  "IDContacto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "NombreContacto" varchar(100),
  "TelefonoContacto" varchar(15),
  "RelacionContacto" varchar(50)
);

CREATE TABLE "Doctores" (
  "IDDoctor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" varchar(50),
  "Apellido" varchar(50),
  "Especialidad" varchar(100),
  "NumeroTelefono" varchar(15),
  "Correo" varchar(50) UNIQUE,
  "FechaContratacion" date
);

CREATE TABLE "Diagnosticos" (
  "IDDiagnostico" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "IDDoctor" int,
  "FechaDiagnostico" datetime,
  "Enfermedad" varchar(255),
  "Prescripcion" text
);

CREATE TABLE "CuidadosCriticos" (
  "IDCuidadoCritico" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDPaciente" int,
  "TipoCuidadoCritico" cuidadoscriticos_tipo_enum,
  "FechaInicio" datetime,
  "FechaFin" datetime
);

CREATE TABLE "Pacientes" (
  "IDPaciente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" varchar(50),
  "Apellido" varchar(50),
  "FechaNacimiento" date,
  "Genero" pacientes_genero_enum,
  "Direccion" text,
  "NumeroTelefono" varchar(15),
  "Correo" varchar(50) UNIQUE,
  "FechaRegistro" datetime
);

CREATE TABLE "AsignacionesEquipamiento" (
  "IDAsignacionEquipo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IDEquipo" int,
  "IDPaciente" int,
  "FechaAsignacion" datetime,
  "FechaDevolucion" datetime
);

ALTER TABLE "Pagos" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "Alergias" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "HabitacionesPacientes" ADD FOREIGN KEY ("IDHabitacion") REFERENCES "Habitaciones" ("IDHabitacion");

ALTER TABLE "Diagnosticos" ADD FOREIGN KEY ("IDDoctor") REFERENCES "Doctores" ("IDDoctor");

ALTER TABLE "GruposApoyoPacientes" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "LlamadasSoporte" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "GruposApoyoPacientes" ADD FOREIGN KEY ("IDGrupoApoyo") REFERENCES "GruposApoyo" ("IDGrupoApoyo");

ALTER TABLE "HistorialMedicacion" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "ContactosEmergencia" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "TurnosPersonal" ADD FOREIGN KEY ("IDPersonal") REFERENCES "Enfermeras" ("IDEnfermera");

ALTER TABLE "AsignacionesPersonal" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "Inmunizaciones" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "CuidadosUrgencias" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "RegistrosMedicos" ADD FOREIGN KEY ("IDDoctor") REFERENCES "Doctores" ("IDDoctor");

ALTER TABLE "AsignacionesEquipamiento" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "Auxiliares" ADD FOREIGN KEY ("IDDoctorAsignado") REFERENCES "Doctores" ("IDDoctor");

ALTER TABLE "AsignacionesEquipamiento" ADD FOREIGN KEY ("IDEquipo") REFERENCES "EquipamientoMedico" ("IDEquipo");

ALTER TABLE "Enfermeras" ADD FOREIGN KEY ("IDDoctorAsignado") REFERENCES "Doctores" ("IDDoctor");

ALTER TABLE "Citas" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "Diagnosticos" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "HabitacionesPacientes" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "CuidadosCriticos" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "Citas" ADD FOREIGN KEY ("IDDoctor") REFERENCES "Doctores" ("IDDoctor");

ALTER TABLE "RegistrosMedicos" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");

ALTER TABLE "ResumenesAlta" ADD FOREIGN KEY ("IDPaciente") REFERENCES "Pacientes" ("IDPaciente");
